title: 智能设计 @ 北理工
description: 智能设计 @ 北理工
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - index.md
 - about.md

# Build settings
theme: jekyll-theme-leap-day

plugins:
 - jekyll-feed
 - jekyll-seo-tag
